FROM debian
COPY . /app
RUN apt-get update
RUN apt-get -y install openjdk-8-jdk
CMD ["java", "-jar", "/app/target/app.jar"]










#------ MALA PRACTICA 1: COPIAS ANTES DE INSTALACIONES 
FROM debian
RUN apt-get update
RUN apt-get -y install openjdk-8-jdk
COPY . /app
CMD ["java", "-jar", "/app/target/app.jar"]


#------ MALA PRACTICA 2: COPIAS DE EL DIRECTORIO COMPLETO 
FROM debian
RUN apt-get update
RUN apt-get -y install openjdk-8-jdk
COPY target/app.jar /app
CMD ["java", "-jar", "/app/target/app.jar"]

#------ MALA PRACTICA 3: UPDATE E INSTALL SEPARADOS
FROM debian
RUN apt-get update && -y install \
    openjdk-8-jdk
COPY target/app.jar /app
CMD ["java", "-jar", "/app/target/app.jar"]

#------ MALA PRACTICA 5: MANTENER CACHE DE ARCHIVOS DE PAQUETES : OPTIMIZACION
FROM debian
RUN apt-get update && -y install \
    openjdk-8-jdk \
    && rm -rf /var/lib/apt/list/*
COPY target/app.jar /app
CMD ["java", "-jar", "/app/target/app.jar"]

#------ MALA PRACTICA 6: NO REUTILIZAR LO YA HECHO
FROM openjdk
COPY target/app.jar /app
CMD ["java", "-jar", "/app/target/app.jar"]


#------ MALA PRACTICA 7: UTILIZAR EL LATEST, ESTO ES MUY IMPORTANTE!!!!!
FROM openjdk:8
COPY target/app.jar /app
CMD ["java", "-jar", "/app/target/app.jar"]


#------ MALA PRACTICA 8: NO UTILIZAR LOS ALPINE
FROM openjdk:8-jre-alpine
COPY target/app.jar /app
CMD ["java", "-jar", "/app/target/app.jar"]


#------ MALA PRACTICA 9: DELEGAR A LA MAQUINA LOCAL LA CONSTRUCCION DE LA IMAGEN, NO PORTABILIDAD
FROM maven:3.8-jdk-8-alpine
COPY pom.xml /app/
COPY src  /app/src
RUN cd /app && mvn -e -B package
CMD ["java", "-jar", "/app/target/app.jar"]

#------ MALA PRACTICA 10: NO USAR WORKDIRS
FROM maven:3.8-jdk-8-alpine
WORKDIR /app
COPY pom.xml .
COPY src  ./src
RUN cd /app && mvn -e -B package
CMD ["java", "-jar", "/app/target/app.jar"]

#------ MALA PRACTICA 11: NO USAR  MULTISTAGE
FROM maven:3.6-jdk-8-alpine as builder
WORKDIR /app
COPY pom.xml .
COPY src  ./src
RUN cd /app && mvn -e -B package
CMD ["java", "-jar", "/app/target/app.jar"]

FROM openjdk:8-jre-alpine
COPY --from=builder /app/target/app.jar
CMD ["java","-jar","app.jar"]